# Generated by Django 2.2.6 on 2019-10-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('predio', models.TextField()),
                ('ala', models.TextField()),
                ('andar', models.IntegerField()),
            ],
        ),
    ]
