# Generated by Django 2.2.6 on 2019-11-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciadorDeLeitos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leito',
            name='status_limpeza',
            field=models.CharField(choices=[('AL', 'Aguardando limpeza'), ('EL', 'Em limpeza'), ('LI', 'Limpo')], default='LI', max_length=2),
        ),
    ]
